FROM python:3.8-slim
RUN apt update
RUN apt-get install build-essential python-dev-is-python3 -y
RUN mkdir -p /progSpros_back
WORKDIR /progSpros_back

COPY ./requirements.txt /progSpros_back

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000